import type { BiomarkerKey } from '../types/session'

export type QuestionAnswerType = 'number' | 'date' | 'select' | 'multiselect' | 'text'
export type QuestionDisplayLevel =
  | 'base'
  | 'flag-follow-up'
  | 'biomarker-based'
  | 'daily-context'
  | 'medication-adherence'

export interface QuestionDefinition {
  id: string
  code: string
  label: string
  type: QuestionAnswerType
  purpose?: string
  options?: string[]
  relatedBiomarkers?: BiomarkerKey[]
  level: QuestionDisplayLevel
  required: boolean
}

const androgenBiomarkers: BiomarkerKey[] = ['totalTestosterone', 'dheas']
const menstrualBiomarkers: BiomarkerKey[] = ['amh', 'lhFshRatio']
const metabolicBiomarkers: BiomarkerKey[] = ['fastingGlucose', 'fastingInsulin', 'ldlC']

export const questionBank: QuestionDefinition[] = [
  {
    id: 'q1-age',
    code: 'Q1',
    label: 'What is your age?',
    type: 'number',
    purpose: 'User profile and monitoring context',
    level: 'base',
    required: true,
  },
  {
    id: 'q2-current-weight',
    code: 'Q2',
    label: 'What is your current weight (kg)?',
    type: 'number',
    purpose: 'Weight trend monitoring',
    level: 'base',
    required: true,
  },
  {
    id: 'q3-height',
    code: 'Q3',
    label: 'What is your height (cm)?',
    type: 'number',
    purpose: 'BMI calculation if needed',
    level: 'base',
    required: true,
  },
  {
    id: 'q4-cycle-regularity-3-months',
    code: 'Q4',
    label: 'How regular has your menstrual cycle been in the past 3 months?',
    type: 'select',
    options: ['Regular', 'Sometimes irregular', 'Often irregular', 'No period in the past 3 months', 'Not sure'],
    level: 'base',
    required: true,
  },
  {
    id: 'q5-usual-cycle-length',
    code: 'Q5',
    label: 'What is your usual cycle length?',
    type: 'select',
    options: ['Less than 21 days', '21-35 days', 'More than 35 days', 'Irregular / changes often', 'Not sure'],
    level: 'base',
    required: true,
  },
  {
    id: 'q6-last-menstrual-period',
    code: 'Q6',
    label: 'When was the first day of your last menstrual period?',
    type: 'date',
    purpose: 'Cycle monitoring',
    level: 'base',
    required: true,
  },
  {
    id: 'q7-menstrual-flow',
    code: 'Q7',
    label: 'How would you describe your menstrual flow?',
    type: 'select',
    options: ['Light', 'Moderate', 'Heavy', 'Varies', 'Not sure'],
    level: 'base',
    required: true,
  },
  {
    id: 'q8-pelvic-pain',
    code: 'Q8',
    label: 'Have you experienced pelvic pain, cramps, or discomfort recently?',
    type: 'select',
    options: ['None', 'Mild', 'Moderate', 'Severe'],
    level: 'base',
    required: true,
  },
  {
    id: 'q9-acne',
    code: 'Q9',
    label: 'Have you noticed increased acne recently?',
    type: 'select',
    options: ['No', 'Mild', 'Moderate', 'Severe', 'Not sure'],
    relatedBiomarkers: androgenBiomarkers,
    level: 'biomarker-based',
    required: true,
  },
  {
    id: 'q10-unwanted-hair',
    code: 'Q10',
    label: 'Have you noticed increased unwanted facial or body hair?',
    type: 'select',
    options: ['No', 'Mild', 'Moderate', 'Severe', 'Not sure'],
    relatedBiomarkers: androgenBiomarkers,
    level: 'biomarker-based',
    required: true,
  },
  {
    id: 'q11-hair-thinning',
    code: 'Q11',
    label: 'Have you noticed hair thinning or increased hair fall recently?',
    type: 'select',
    options: ['No', 'Mild', 'Moderate', 'Severe', 'Not sure'],
    relatedBiomarkers: androgenBiomarkers,
    level: 'biomarker-based',
    required: true,
  },
  {
    id: 'q12-hair-growth-location',
    code: 'Q12',
    label: 'If you noticed unwanted hair growth, where is it mostly observed?',
    type: 'multiselect',
    options: ['Upper lip', 'Chin', 'Chest', 'Abdomen', 'Back', 'Arms or legs', 'Other', 'Not applicable'],
    relatedBiomarkers: androgenBiomarkers,
    level: 'biomarker-based',
    required: true,
  },
  {
    id: 'q13-skin-hair-change',
    code: 'Q13',
    label: 'Have these skin or hair-related symptoms changed compared to your previous session?',
    type: 'select',
    options: ['Improved', 'Same', 'Worse', 'First time logging', 'Not sure'],
    relatedBiomarkers: androgenBiomarkers,
    level: 'biomarker-based',
    required: true,
  },
  {
    id: 'q14-missed-periods',
    code: 'Q14',
    label: 'Have you missed any menstrual periods in the past 3 months?',
    type: 'select',
    options: ['No', 'Yes, missed 1 period', 'Yes, missed 2 or more periods', 'No period in the past 3 months', 'Not sure'],
    relatedBiomarkers: menstrualBiomarkers,
    level: 'biomarker-based',
    required: true,
  },
  {
    id: 'q15-predictable-periods',
    code: 'Q15',
    label: 'Do your periods usually come at predictable intervals?',
    type: 'select',
    options: ['Yes', 'Sometimes', 'Rarely', 'No', 'Not sure'],
    relatedBiomarkers: menstrualBiomarkers,
    level: 'biomarker-based',
    required: true,
  },
  {
    id: 'q16-spotting',
    code: 'Q16',
    label: 'Have you experienced spotting or bleeding between periods?',
    type: 'select',
    options: ['No', 'Yes, once', 'Yes, more than once', 'Not sure'],
    relatedBiomarkers: menstrualBiomarkers,
    level: 'biomarker-based',
    required: true,
  },
  {
    id: 'q17-cycle-comparison',
    code: 'Q17',
    label: 'Compared to your previous cycle, how would you describe your current cycle pattern?',
    type: 'select',
    options: ['More regular', 'About the same', 'More irregular', 'Not sure', 'First time logging'],
    relatedBiomarkers: menstrualBiomarkers,
    level: 'biomarker-based',
    required: true,
  },
  {
    id: 'q18-weight-changes',
    code: 'Q18',
    label: 'Have you noticed unexplained weight changes recently?',
    type: 'select',
    options: ['No', 'Weight gain', 'Weight loss', 'Weight fluctuates', 'Not sure'],
    relatedBiomarkers: metabolicBiomarkers,
    level: 'biomarker-based',
    required: true,
  },
  {
    id: 'q19-fatigue-frequency',
    code: 'Q19',
    label: 'How often have you experienced fatigue recently?',
    type: 'select',
    options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Almost daily'],
    relatedBiomarkers: ['fastingGlucose', 'fastingInsulin'],
    level: 'biomarker-based',
    required: true,
  },
  {
    id: 'q20-cravings-hunger',
    code: 'Q20',
    label: 'Have you experienced frequent cravings or increased hunger recently?',
    type: 'select',
    options: ['No', 'Mild', 'Moderate', 'Severe', 'Not sure'],
    relatedBiomarkers: ['fastingGlucose', 'fastingInsulin'],
    level: 'biomarker-based',
    required: true,
  },
  {
    id: 'q21-physical-activity',
    code: 'Q21',
    label: 'How would you describe your physical activity recently?',
    type: 'select',
    options: ['Mostly inactive', 'Light activity', 'Moderate activity', 'Active', 'Not sure'],
    relatedBiomarkers: ['ldlC'],
    level: 'biomarker-based',
    required: true,
  },
  {
    id: 'q22-food-notes',
    code: 'Q22',
    label: 'Would you like to add food or meal notes for this session?',
    type: 'text',
    purpose: 'Lifestyle context only, not diet recommendation',
    relatedBiomarkers: metabolicBiomarkers,
    level: 'biomarker-based',
    required: false,
  },
  {
    id: 'q23-activity-notes',
    code: 'Q23',
    label: 'Would you like to add exercise or activity notes for this session?',
    type: 'text',
    purpose: 'Lifestyle context only, not exercise prescription',
    relatedBiomarkers: ['ldlC'],
    level: 'biomarker-based',
    required: false,
  },
  {
    id: 'q24-sleep-hours',
    code: 'Q24',
    label: 'How many hours of sleep did you usually get recently?',
    type: 'select',
    options: ['Less than 5 hours', '5-6 hours', '7-8 hours', 'More than 8 hours', 'Varies'],
    level: 'daily-context',
    required: false,
  },
  {
    id: 'q25-sleep-quality',
    code: 'Q25',
    label: 'How would you rate your sleep quality recently?',
    type: 'select',
    options: ['Poor', 'Fair', 'Good', 'Very good', 'Not sure'],
    level: 'daily-context',
    required: false,
  },
  {
    id: 'q26-stress-level',
    code: 'Q26',
    label: 'How would you describe your stress level recently?',
    type: 'select',
    options: ['Low', 'Moderate', 'High', 'Very high', 'Not sure'],
    level: 'daily-context',
    required: false,
  },
  {
    id: 'q27-mood',
    code: 'Q27',
    label: 'How would you describe your mood recently?',
    type: 'select',
    options: ['Stable', 'Sometimes low', 'Often low', 'Anxious or stressed', 'Varies', 'Prefer not to say'],
    level: 'daily-context',
    required: false,
  },
  {
    id: 'q28-other-symptoms',
    code: 'Q28',
    label: 'Have you experienced bloating, cramps, cravings, or other PCOS-related symptoms recently?',
    type: 'multiselect',
    options: [
      'Bloating',
      'Cramps',
      'Cravings',
      'Fatigue',
      'Acne',
      'Hair growth concern',
      'Hair thinning',
      'Weight change',
      'Mood changes',
      'None',
      'Other',
    ],
    level: 'daily-context',
    required: false,
  },
  {
    id: 'q29-medication-scheduled',
    code: 'Q29',
    label: 'Did you take your physician-prescribed medication as scheduled?',
    type: 'select',
    options: ['Taken', 'Skipped', 'Missed', 'Not scheduled today'],
    level: 'medication-adherence',
    required: true,
  },
  {
    id: 'q30-medication-note',
    code: 'Q30',
    label: 'Would you like to add a note about your medication intake?',
    type: 'text',
    purpose: 'Reminder and adherence tracking only',
    level: 'medication-adherence',
    required: false,
  },
]
